name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
      - 'hotfix'
  - title: '🧰 Maintenance'
    labels:
      - 'chore'
      - 'chore: major'
      - 'chore: minor'
      - 'chore: patch'
      - 'refactor'
      - 'restructure'
      - 'cleanup'
      - 'ci'
      - 'perf'
      - 'build'
      - 'security'
      - 'infrastructure'
  - title: '📦 Dependencies'
    labels:
      - 'renovate'
  - title: '📚 Documentation'
    labels:
      - 'docs'
      - 'documentation'
  - title: 'Other'
    labels:
      - '*'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - 'release: major'
  minor:
    labels:
      - 'release: minor'
  patch:
    labels:
      - 'release: patch'
template: |
  ## What's Changed

  $CHANGES

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION
exclude-contributors:
  - 'renovate'
  - 'renovate[bot]'
  - 'dependabot'
  - 'dependabot[bot]'
