changelog:
  categories:
    - title: "🚀 Features"
      labels:
        - enhancement
        - feature

    - title: "🐛 Bug Fixes"
      labels:
        - fix
        - hotfix
        - bugfix

    - title: "🧰 Maintenance"
      labels:
        - maintenance
        - refactor
        - chore
        - chore:deps
        - chore:devdeps
        - chore:ci
        - ci

    - title: "📝 Documentation"
      labels:
        - documentation

    - title: "🏗️ Infrastructure"
      labels:
        - infrastructure

    - title: "🧪 Tests"
      labels:
        - test

    - title: "📦 Dependencies"
      labels:
        - dependencies
        - renovate
        - bump:major
        - bump:minor
        - bump:patch
