changelog:
  categories:
    - title: "🚀 Features"
      labels:
        - enhancement
        - feature

    - title: "🐛 Bug Fixes"
      labels:
        - bug
        - fix
        - hotfix
        - bugfix

    - title: "🧰 Maintenance"
      labels:
        - maintenance
        - refactor
        - chore

    - title: "📝 Documentation"
      labels:
        - documentation

    - title: "🏗️ Infrastructure"
      labels:
        - infrastructure

    - title: "🧪 Tests"
      labels:
        - test

    - title: "📦 Dependencies"
      labels:
        - dependencies
