name: 'issue-validator'
description: 'auto close issue if it does not meet the conditions'
author: 'Okabe-Junya'
inputs:
  title:
    description: 'title for issue'
    required: false
    default: ''
  body:
    description: 'body for issue'
    required: false
    default: ''
  title-regex-flags:
    description: 'regex flags for title'
    required: false
    default: ''
  body-regex-flags:
    description: 'regex flags for body'
    required: false
    default: ''
  token:
    description: 'token for github'
    default: ${{ github.server_url == 'https://github.com' && github.token || '' }}
  is-auto-close:
    description: 'auto close issue if it does not meet the conditions'
    required: false
    default: 'false'
outputs:
  result:
    description: 'result of validation'

runs:
  using: 'node20'
  main: 'dist/index.js'
