name: 'issue-validator'
description: 'auto close issue if it does not meet the conditions'
author: 'Okabe-Junya'
branding:
  icon: 'alert-triangle'
  color: 'gray-dark'
inputs:
  title:
    description: 'title for issue'
    required: false
    default: ''
  body:
    description: 'body for issue'
    required: false
    default: ''
  title-regex-flags:
    description: 'regex flags for title. if you want to use regex, you must set title and title-regex-flags: "true"'
    required: false
    default: ''
  body-regex-flags:
    description: 'regex flags for body. if you want to use regex, you must set body and body-regex-flags: "true"'
    required: false
    default: ''
  github-token:
    description: 'token for github'
    default: ${{ github.server_url == 'https://github.com' && github.token || '' }}
  issue-type:
    description: 'validate for issue or pull request. if you want to validate pull request, you must set issue-type: "pull_request". Both issue and pull request are validated, if you set issue-type: "both". default is "issue"'
    required: false
    default: 'issue'
  is-auto-close:
    description: 'auto close issue if it does not meet the conditions'
    required: false
    default: 'false'
outputs:
  result:
    description: 'result of validation'

runs:
  using: 'node20'
  main: 'dist/index.js'
